alias python="python3"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias gp='git push'
alias ga='git add'
alias gs='git status'
alias gpo='git push origin'
alias gd='git diff'
alias gdc='git diff --color-words'
alias gl='git log'
alias gri='git rebase -i'
alias gc='git commit -a'
alias gch='git checkout'
alias gb='git branch'
alias sb='source ~/.bashrc'
alias gpu="git pull upstream main"
alias gcb="git checkout -b"
alias gcm="git checkout main"
alias lpython="./src/bin/lpython"
alias lp="cd Applications/oss/lpython && conda activate lp"
alias ast="lpython --show-ast --indent --show-stacktrace"
alias asr="lpython --show-asr --indent --show-stacktrace"
alias cpp="lpython --show-cpp"
alias llvm="lpython --show-llvm"
